// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxp7Y5Oim8rwA3EqEpIRd83mF7Pt7UQGg',
    appId: '1:818415433895:web:945881632533d2dd1d0382',
    messagingSenderId: '818415433895',
    projectId: 'chatapp493',
    authDomain: 'chatapp493.firebaseapp.com',
    storageBucket: 'chatapp493.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiUgikZyS7UcaT36mP9qCUQoAXaRgT7bw',
    appId: '1:818415433895:android:7ea629ad2389301b1d0382',
    messagingSenderId: '818415433895',
    projectId: 'chatapp493',
    storageBucket: 'chatapp493.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR-6nRtk4KWE93UTBI82shlDMKZN4ExJE',
    appId: '1:818415433895:ios:83354351d8ffb66d1d0382',
    messagingSenderId: '818415433895',
    projectId: 'chatapp493',
    storageBucket: 'chatapp493.firebasestorage.app',
    iosClientId: '818415433895-711dfdcnq7jp367ho9730v0pgefk4ug5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR-6nRtk4KWE93UTBI82shlDMKZN4ExJE',
    appId: '1:818415433895:ios:83354351d8ffb66d1d0382',
    messagingSenderId: '818415433895',
    projectId: 'chatapp493',
    storageBucket: 'chatapp493.firebasestorage.app',
    iosClientId: '818415433895-711dfdcnq7jp367ho9730v0pgefk4ug5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxp7Y5Oim8rwA3EqEpIRd83mF7Pt7UQGg',
    appId: '1:818415433895:web:bac146cd257c524d1d0382',
    messagingSenderId: '818415433895',
    projectId: 'chatapp493',
    authDomain: 'chatapp493.firebaseapp.com',
    storageBucket: 'chatapp493.firebasestorage.app',
  );
}
